name: Test

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Move to tobeprocessed
    strategy:
      matrix:
        operation: ["insert", "update"]
        hour:
          [
            "00",
            "01",
            "02",
          ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        run: |
          echo "file_${{ matrix.operation }}-$(date +"%Y-%m-%d")"
